apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: default
spec:
  encryptedData:
    pass: AgAo1bXkxUeco+k40AVpYLLXeWG4jEEaMsPsViT31XG3UeddmA2pMyn6QCFrCTQwfS8z4gNl/D4GPu98pUMaiBuui8T2IdxE8PVUXRIayVG3/mVs9riw4LUDV5VPqUKk5BEMUN+N2ZF4MzpuK9+6xdkS1VDAwoBNOFaLrVKyPE0VG19Zd0IMh6NM+XSZnJHwg89CYiLAl/lCyH7hB/KqcpycTKEiUxdkev7S7LoQvVnax28pHJd8WwlnkgT24D88NlOSGhNat4Mohoa+dAFdztumRj6vDNGCV2llLS64NMAtkSLMcipoH2p7fLB++siwlZyxtfr37adY3kggLmZ3p7U2HJG7f4ilqAJhGHq/i3Ao610oBtLYJaPHtcC2JEP/EEB7s275JfY7dC1GW78SzFUOl46vRINVI9gIVs6jDUhcZ92RfDz2R9A1/mtWNOYYs9YpedttvL4PgelDh039APDjovgNy9iQ/AFjoSA0bTaCeorFYvdUgIUJ5DvGa35FkrWOAHHPvRvORpHeReds8ApbAZ+pavz/U1QV14LFmcHbslAve66SRxd+22jit82QtC0Es6PtA5LwGWVjIFaoV/YIKOrX71NPLRsZAtg9UbhQ9ATDOGU07Vvqj6njGLhsMTMkqXehlOVtuW/HbMRkrpbu+wjR7bb8Zvy+IrHHTMn5nobOOPsRr5iQ71HKo7rpATlslm9xr6yL9DNx
  template:
    metadata:
      name: app-secret
      namespace: default

